config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :instigator do
    resources :cats, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cats
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/instigator/cats_controller.rb
class Instigator::CatsController < ApplicationController
  before_action :authenticate_user!

  def new
    @cat = Cat.new
  end

  def create
    @cat = current_user.cats.create(cat_params)
    redirect_to instigator_cat_path(@cat)
  end

  def show
    @cat = Cat.find(params[:id])
  end

  private

  def cat_params
    params.require(:cat).permit(:title, :description)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instigator/cats_helper.rb
module Instigator::CatsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/instigator/cats/new.html.erb
<h1>Add a New Cat</h1>
<%= simple_form_for @cat, url: instigator_cats_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>

app/views/instigator/cats/show.html.erb
<h1><%= @cat.title %></h1>
<h2><%= @cat.description %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nerve</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">nerve.</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/sign_up">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/sign_in">Log In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>


<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1 class="p1">Welcome to my Page!</h1>
<h2 class="p2">By: m.c.v.</h2>

<%= link_to 'instigate', new_instigator_cat_path %>